name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: SonarCloud Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@e2a1ee7c31ee491f1e09c74535b1c0d3e9f5cd82
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        with:
          args: 'e846d6f1b118b620f3a6d070be711e951784e262'
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: main
          
