name: SonarCloud Scan

on: push

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            - Dsonar.projectKey=testFixBug
            - Dsonar.organization=Lorentin
